[google_credentials]
type = "service_account"
project_id = "streamlit-sheets-bot-473709"
private_key_id = "bfaf931fad7587a3c9fa7ebe0cb034195fa6c627"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDRacKRAYfasPBF
nHJawJhB9+Me8byf4bvUjusGPb0KbZkf50faHVrK0DvHx/4Hnz2lAeE/9f7PhVTe
PyiR+dXjIRDcigxMbuhA2kne1qQdyX68UCuz3yQz2Wbrl210AGJfcHQHSDxK4p8V
Xwn77zgKSqH9rWQwHPNLIvAVv10V5dm+F4wAZRhum0cHnBr9Xj3It218ZV4JecUT
M8WSidD6EVL+o/S7TTHxwxj5kJ12IbN6WlfLt5gh8ACstZIQbvzpCUmnFqJKjUj+
WElkbKhsNyUPTo2lqQnNCB0NkTkARKR8vVSRs3ZOIsQrlvTAQEd1nYMuwaA/hllS
A/j25SwHAgMBAAECggEANnxBatAOpFhQE5SKblFY7CUOe2EjFig54iqTPMr4cgul
AReAauAjXMyEGU1QK3SDqfiMvkMHWsASnkapjB2ISHG0fOUQIRzkIeeJu8h15+gi
qOVlEYY32aOxcw+xozJsZe+QyMpDIarIAFv7cYjCuG7FqgagoCIQLRb4h3gERKtR
6QKVZFtH4/4CkojigQn7VO2ZtnR+Uzvvt4DL89NrMLFtIy2SIXsWnoMOwJ/GK3To
V7oVANpuGIZH3mmit5drXK7QTiLM6EVUDgnWCFXrh7qhvJeLTdA2f4d8wQei7wrg
aD4em1NDQ310Rx9X2OV7Adu6YJ3PQcrXxoOeemzJuQKBgQD02A32EvSk5stxYQ1X
zyd5gFaJM2HY9Ks+Mlz3XEpbkjT9vqTYoZpjfBaIkk8YJlE8+VL7W1nn7djm++GQ
nErG+kU9q1DAM6FhRqSgq+6orafEJsJe53hy4BOwY+radZBBwRYk6A/wst4fucFb
y/sIGX9LjFMA9F4xWoB3NvGv+QKBgQDa9G2F/840telsgQZjXdQ2raElj/ihhzRZ
HGtZItKS+Qm2n/0bvUIOBk9ZireQ9Wr18Vg99I8308JMkWuQPBJzWckotleaHVBL
YrpYsIF77rhu3CRxJD4kVSe0rnLC8Nu2wN6rlWcZcGjGhCvdVhuG4NjzIYZWdG8+
R2D2FHy7/wKBgA+y0qJWcM0p5x1r5ZkdtSA7NFEztDBe76PbQs6xYisg4rjqQlOJ
eQar7B3xk5Su0EKikcl///G49FFLERlejATaAxqDI3hPVyePifqrS3ARQlJ3UbsY
CEcFSv3iSiqboxY0NSFEp9D9BvTtyhICsCPCzsCfTKsg//EWJmp+YVyxAoGAGtkF
5Pxs6IG10ZwwkFadAudfbx+sOQI/JP4bG57teyAWVNJhUtluFBIqAKzFvXyaVPX3
AAHQ3eOVW5YpPlJfYM2NoPRa4YbepZ/BgcaC2hN3ggB0Z3suM35NlBYf9E9cYZhc
tWVocvIZpt3mEwnP7kX71DQ0KL22NkjCVupEMTkCgYBDaq2Sv+A1SqCqhEEN0j/Q
bE4bQL4T0hk6vcUSL3CnQTh6IsXxSml33a3yu3gkORsLEnBtE9fO2vDn70NNNjGs
vw2allxjBAAIIp3ID1ZrpNWxgjZYI6R2fvUTDMELQzcoiE/Lf6eXN5KE6PlmPlZ5
2g+l0aeSQK0So/ilWKlJCw==
-----END PRIVATE KEY-----
"""
client_email = "streamlit-sheets-bot@streamlit-sheets-bot-473709.iam.gserviceaccount.com"
client_id = "106255093630582995088"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-sheets-bot%40streamlit-sheets-bot-473709.iam.gserviceaccount.com"
